name: squad_ci
description: "SQUAD CI - Application sociale ivoirienne"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2

  # Audio
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1

  # State Management
  provider: ^6.1.2

  # UI
  cached_network_image: ^3.4.1
  video_player: ^2.9.1

  # Utilities
  path_provider: ^2.1.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
